---
- hosts: Apache
  become: true
  pre_tasks:
    - name: update repo index (Redhat)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Redhat"
    
    - name: update repo index (Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == "Debian"
  
  tasks:
    - name: Install epel repo for RedHat family OS
      tags: epel,RedHat
      dnf: name=epel-release state=present
      when: ansible_os_family == "RedHat"

    - name: Install Apache and PHP RedHat family OS
      tags: apache,httpd,php,RedHat
      dnf: 
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"
      
    - name: Start and enable Apache RedHat family OS
      tags: RedHat,httpd,service
      service: 
        name: httpd 
        state: started 
        enabled : yes
        daemon-reload: yes
      when: ansible_os_family == "RedHat"
      
    - name: Install Apache and PHP for Debian Family OS
      tags: apache,apache2,Debian
      apt: 
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"